#!/usr/bin/env php
<?php

require_once("vendor/autoload.php");

use uarsoftware\dbpatch\Command\TestCommand;
use uarsoftware\dbpatch\Command\AddCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new TestCommand);
$application->add(new AddCommand);
$application->run();

