#!/usr/bin/env php
<?php

require_once("vendor/autoload.php");

use uarsoftware\dbpatch\Command\CreateCommand;
use uarsoftware\dbpatch\Command\RecordCommand;
use uarsoftware\dbpatch\Command\ViewCommand;
use uarsoftware\dbpatch\Command\InitCommand;
use uarsoftware\dbpatch\Command\PatchCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CreateCommand);
$application->add(new RecordCommand);
$application->add(new ViewCommand);
$application->add(new InitCommand);
$application->add(new PatchCommand);
$application->run();

